name: larkmusic
description: LarkMusic client
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.4+4

environment:
  sdk: '>=3.2.3 <4.0.0'
#  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  window_manager: ^0.3.7
  dio: ^5.4.0
  pretty_dio_logger: ^1.3.1
  shared_preferences: ^2.2.2
  flutter_riverpod: ^2.4.9
  go_router: ^13.0.0
  oktoast: ^3.4.0
  just_audio: ^0.9.36
  just_audio_web: ^0.4.9
  just_audio_windows: ^0.2.0
  just_audio_mpv: ^0.1.7
  just_audio_background: ^0.0.1-beta.11
  audio_session: ^0.1.18
  audio_video_progress_bar: ^2.0.1
  flutter_lyric: ^2.0.4+6
  easy_refresh: ^3.3.4
  crypto: ^3.0.3
  package_info_plus: ^5.0.1
  system_tray: ^2.0.3
  flutter_context_menu: ^0.1.3
  url_strategy: ^0.2.0
  flutter_dotenv: ^5.1.0
  loading_animation_widget: ^1.2.0+4
  logger: ^2.0.2+1
  flutter_list_view: ^1.1.22
  url_launcher: ^6.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  flutter_lints: ^3.0.1


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/.env

flutter_intl:
  enabled: true
